### ISSUE TITLE
troubles with non-ascii encoding

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#15]
Gathering logs used by preupgrade assistant:
All installed packages : 01/5 ...runningTraceback (most recent call last):
  File "/usr/bin/preupg", line 34, in <module>
    sys.exit(main())
  File "/usr/bin/preupg", line 21, in main
    ret = app.run()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 650, in run
    if not self.common.common_results():
  File "/usr/lib/python2.7/site-packages/preup/common.py", line 78, in common_results
    run_subprocess(cmd, output=common_file_path, shell=True)
  File "/usr/lib/python2.7/site-packages/preup/utils.py", line 95, in run_subprocess
    stdout += stdout_data.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 37: ordinal not in range(128)

**Comment by pirat89** [comment]
Fixed: https://github.com/phracek/preupgrade-assistant/commit/ce7e0fcd9f46b0721b6dae4e3878eccd441a75aa

**Comment by pirat89** [comment]
Many tests are broken now. Check it

**Comment by pirat89** [comment]
Fixed by commit https://github.com/phracek/preupgrade-assistant/commit/01676adea0d7e65496e5c670bceb3eb8a5f68b0e

**Comment by pirat89** [comment]
Traceback (most recent call last):
  File "/usr/bin/preupg", line 34, in <module>
    sys.exit(main())
  File "/usr/bin/preupg", line 21, in main
    ret = app.run()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 664, in run
    tarball_path = self.scan_system()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 462, in scan_system
    assessment_dir = self.generate_report()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 437, in generate_report
    generated_dir = xccdf_compose.generate_xml()
  File "/usr/lib/python2.7/site-packages/preuputils/compose.py", line 53, in generate_xml
    target_tree = ComposeXML.run_compose(target_tree, self.dir_name)
  File "/usr/lib/python2.7/site-packages/preuputils/compose.py", line 300, in run_compose
    group_xmls = cls.collect_group_xmls(dir_name, content=content, level=0)
  File "/usr/lib/python2.7/site-packages/preuputils/compose.py", line 95, in collect_group_xmls
    cls.collect_group_xmls(new_dir, level=level + 1))
  File "/usr/lib/python2.7/site-packages/preuputils/compose.py", line 84, in collect_group_xmls
    oscap_group.write_xml()
  File "/usr/lib/python2.7/site-packages/preuputils/oscap_group_xml.py", line 83, in write_xml
    self.rule = xml_utils.prepare_sections()
  File "/usr/lib/python2.7/site-packages/preuputils/xml_utils.py", line 222, in prepare_sections
    self.create_xml_from_ini(main)
  File "/usr/lib/python2.7/site-packages/preuputils/xml_utils.py", line 342, in create_xml_from_ini
    function(key, k)
  File "/usr/lib/python2.7/site-packages/preuputils/xml_utils.py", line 249, in fnc_check_script
    self.check_script_modification(key, name)
  File "/usr/lib/python2.7/site-packages/preuputils/xml_utils.py", line 206, in check_script_modification
    author=key['author'] if 'author' in key else "")
  File "/usr/lib/python2.7/site-packages/preuputils/script_utils.py", line 128, in update_check_script
    lines = [x for x in lines if func not in x.strip()]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 10: ordinal not in range(128)

**Comment by pirat89** [comment]
Well, after many tests this should be really fixed now: https://github.com/phracek/preupgrade-assistant/commit/dbf3dbc70718968c3d59ff2fc27c2074c7642bcd
