### ISSUE TITLE
setup.py tests crash on python3.4

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#36]
```bash
$ python3 ./setup.py test
running test
running egg_info
writing top-level names to preupgrade_assistant.egg-info/top_level.txt
writing preupgrade_assistant.egg-info/PKG-INFO
writing dependency_links to preupgrade_assistant.egg-info/dependency_links.txt
reading manifest file 'preupgrade_assistant.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Makefile'
warning: no files found matching '*' under directory 'preup_ui/lib'
writing manifest file 'preupgrade_assistant.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 68, in <module>
    test_suite      = 'tests.suite',
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 138, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 118, in with_project_on_sys_path
    func()
  File "/usr/lib/python3.4/site-packages/setuptools/command/test.py", line 164, in run_tests
    testLoader = cks
  File "/usr/lib64/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib64/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/usr/lib64/python3.4/unittest/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.4/unittest/loader.py", line 146, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.4/unittest/loader.py", line 105, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/pstodulk/special/preupgrade-assistant/tests/__init__.py", line 1, in <module>
    import test_preup
ImportError: No module named 'test_preup'
```

**Comment by pirat89** [comment]
Some parts of code are fixed. However we haven't pykickstart for python 3.4 inside Fedora 22. Pykickstart is available already for Fedora 23.

**Comment by pirat89** [comment]
fixed already in the past
