### ISSUE TITLE
unicode - traceback during scanning with non-ascii characters

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#39]
```
Plugable authentication modules (PAM) +ľš[34m~Mťť
Traceback (most recent call last):
  File "/usr/bin/preupg", line 34, in <module>
    sys.exit(main())
  File "/usr/bin/preupg", line 21, in main
    ret = app.run()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 638, in run
    tarball_path = self.scan_system()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 481, in scan_system
    self.run_scan_process()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 252, in run_scan_process
    self.run_scan(function=self.scanning_progress.show_progress)
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 269, in run_scan
    return run_subprocess(cmd, print_output=False, function=function)
  File "/usr/lib/python2.7/site-packages/preup/utils.py", line 124, in run_subprocess
    function(stdout_data)
  File "/usr/lib/python2.7/site-packages/preup/scanning.py", line 97, in show_progress
    stdout_data.strip()))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-40: ordinal not in range(128)
```

**Comment by pirat89** [comment]
Some tests should be created for this too.
