### ISSUE TITLE
invalid argument 'flush' in print

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#45]
print function for python 2 doesn't know *flush* argument. Should be removed and checked for master and rhel-5 branch too

```python
Traceback (most recent call last):
  File "/usr/bin/preupg", line 34, in <module>
    sys.exit(main())
  File "/usr/bin/preupg", line 21, in main
    ret = app.run()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 600, in run
    tarball_path = self.scan_system()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 443, in scan_system
    self.prepare_xml_for_html()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 315, in prepare_xml_for_html
    self.prepare_for_generation()
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 301, in prepare_for_generation
    self.run_generate(report, report.replace('.xml', '.html'))
  File "/usr/lib/python2.7/site-packages/preup/application.py", line 248, in run_generate
    return run_subprocess(cmd, print_output=True)
  File "/usr/lib/python2.7/site-packages/preup/utils.py", line 136, in run_subprocess
    print (stdout_data, end="", flush=True)
TypeError: 'flush' is an invalid keyword argument for this function
```

**Comment by phracek** [comment]
Fixed by commit https://github.com/phracek/preupgrade-assistant/commit/85df6fdad47437ed30992136b90450bd24fcd0d1
