### ISSUE TITLE
traceback for setup.py

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#66]
On Fedora 22, upstream version of PA
```python
 ./setup.py --help-commands
Traceback (most recent call last):
  File "./setup.py", line 60, in <module>
    test_suite      = 'tests.suite',
  File "/usr/lib64/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 299, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib64/python2.7/distutils/dist.py", line 464, in parse_command_line
    if self.handle_display_options(option_order):
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 679, in handle_display_options
    return _Distribution.handle_display_options(self, option_order)
  File "/usr/lib64/python2.7/distutils/dist.py", line 669, in handle_display_options
    self.print_commands()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 439, in print_commands
    cmdclass = ep.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/pbr/testr_command.py", line 47, in <module>
    from testrepository import commands
ImportError: No module named testrepository
```

**Comment by phracek** [comment]
From the latest upstream version it works:
~~~
$ ./setup.py --help-commands
Standard commands:
  build             build everything needed to install
  build_py          "build" pure Python modules (copy to build directory)
  build_ext         build C/C++ extensions (compile/link to build directory)
  build_clib        build C/C++ libraries used by Python extensions
  build_scripts     "build" scripts (copy and fixup #! line)
  clean             clean up temporary files from 'build' command
  install           install everything from build directory
  install_lib       install all Python modules (extensions and pure Python)
  install_headers   install C/C++ header files
  install_scripts   install scripts (Python or otherwise)
  install_data      install data files
  sdist             create a source distribution (tarball, zip file, etc.)
  register          register the distribution with the Python package index
  bdist             create a built (binary) distribution
  bdist_dumb        create a "dumb" built distribution
  bdist_rpm         create an RPM distribution
  bdist_wininst     create an executable installer for MS Windows
  upload            upload binary package to PyPI
  check             perform some checks on the package

Extra commands:
  develop           install package in 'development mode'
  saveopts          save supplied options to setup.cfg or other config file
  egg_info          create a distribution's .egg-info directory
  upload_docs       Upload documentation to PyPI
  alias             define a shortcut to invoke one or more commands
  easy_install      Find/get/install Python packages
  rotate            delete older distributions, keeping N newest files
  bdist_egg         create an "egg" distribution
  install_egg_info  Install an .egg-info directory for the package
  test              run unit tests after in-place build
  setopt            set an option in setup.cfg or another config file

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

$ 

~~~
