### ISSUE TITLE
traceback in setup.py

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#68]
OS: Fedora 22

```python
$ ./setup.py --help-commands
Traceback (most recent call last):
  File "./setup.py", line 61, in <module>
    test_suite      = 'tests.suite',
  File "/usr/lib64/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 299, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib64/python2.7/distutils/dist.py", line 464, in parse_command_line
    if self.handle_display_options(option_order):
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 679, in handle_display_options
    return _Distribution.handle_display_options(self, option_order)
  File "/usr/lib64/python2.7/distutils/dist.py", line 669, in handle_display_options
    self.print_commands()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 439, in print_commands
    cmdclass = ep.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/pbr/testr_command.py", line 47, in <module>
    from testrepository import commands
ImportError: No module named testrepository

```

**Comment by pirat89** [comment]
oh, wrong report. That's issue of python-pbr package
