### ISSUE TITLE
can't generate kickstart on 32b system (checked only on RHEL-5)

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#93]
```python
Traceback (most recent call last):
  File "/usr/bin/preupg", line 33, in ?
    sys.exit(main())
  File "/usr/bin/preupg", line 20, in main
    ret = app.run()
  File "/usr/lib/python2.4/site-packages/preup/application.py", line 690, in run
    kg.main()
  File "/usr/lib/python2.4/site-packages/preup/kickstart/application.py", line 347, in main
    dummy_ks = self.generate()
  File "/usr/lib/python2.4/site-packages/preup/kickstart/application.py", line 326, in generate
    groups, packages = self.output_packages()
TypeError: unpack non-sequence
```

P.S. That's not same as on 64b machine with installed ospenscap of both archs, which seems are in conflict.

**Comment by pirat89** [comment]
Note: *self.output_packages()* returns *None* object.

**Comment by phracek** [comment]
Fixed by commit https://github.com/phracek/preupgrade-assistant/commit/aaa61fa3e58d6f722bd1d5c394352d924fe7ae13
